### PR TITLE
Reset timeout when active slide changes

### PR DESCRIPTION
**Pull request by NicolaG1993**
This is how I've solved this issue in my App:

- delete play, interval, the if statement that activate setInterval, and the clearInterval as well
- write them inside a new useEffect
- inside the array pass activeSlide

All of this code now gets activated only when a new slide renders on screen, and this will also clear the interval when the component unmount

I haven't tested it so much yet and i'm new to React too, so im not 100% sure this is the best solution, but it seems to work!

### CODE REVIEW

**Comment by DZuz14** [comment]
@NicolaG1993 Just so I'm are clear, your problem is that when clicking one of the left and right arrows, you want the autoplay timer to reset?

**Comment by DZuz14** [comment]
Everything looks good here. Any chance you could touch something else I thought of up? We can probably get rid of multiple conditionals as well. 

```
  useEffect(() => {
    if (!props.autoPlay) return

    const play = () => {
        autoPlayRef.current();
    }

    const interval = setInterval(play, props.autoPlay * 1000);

    return () => {
        clearInterval(interval);
    };
  }, [activeSlide])
```

**Comment by NicolaG1993** [comment]
> @NicolaG1993 Just so I'm clear, your problem is that when clicking one of the left and right arrows, you want the autoplay timer to reset?

Exactly, the problem is this: when you click on one of the two arrows, the timer does not reset so the first transition will always be out of time. At the moment with these changes I no longer encounter this error

**Comment by NicolaG1993** [comment]
> Everything looks good here. Any chance you could touch something else I thought of up? We can probably get rid of multiple conditionals as well.
> 
> ```
>   useEffect(() => {
>     if (!props.autoPlay) return
> 
>     const play = () => {
>         autoPlayRef.current();
>     }
> 
>     const interval = setInterval(play, props.autoPlay * 1000);
> 
>     return () => {
>         clearInterval(interval);
>     };
>   }, [activeSlide])
> ```

I can take a look at it, but at the moment I don't see how to write it shorter.. what do you think?

**Comment by DZuz14** [comment]
@NicolaG1993 It's all good, I will fix it, my snippet was confusing. I am going to merge this in.

**Comment by NicolaG1993** [comment]
Nice, happy to hear that! 🐸

**Pull request merged**
